### ISSUE TITLE
reset timer on item 

### ISSUE THREAD

**Issue by negue** [negue/todo-overlay#28]

**Comment by RascalTwo** [comment]
Hey, I can do this!

***

I'm thinking the command usage would mirror the `stop` command - so it'll work either based on provided `POSITION` or the current timer.

***

Just to ensure I'm clear on the behavior:

- When the timer is running: `reset` would reset it back to 0 and it will continue running from there.

- When the timer is stopped: `reset` would clear the timer entirely.

***

So running these commands:

- `start 1`
- `reset`
- `stop`
- `reset 1`

with a 2 second delay between then results in this:

![gif of starting, resetting, stopping, and resetting the timer](https://user-images.githubusercontent.com/9403665/97914699-4d6ac780-1d1e-11eb-9dd7-e8aa98cb3345.gif)

**Comment by negue** [comment]
woah yes to all you wrote !! 😀  thats a nice behavior using these commands.

Please feel free to create that, thank you :)
